### PR TITLE
Optimized PROPERTY_MATCH query

### PR DESCRIPTION
**Pull request by skavanagh**
Optimized PROPERTY_MATCH query when returning vulnerabilities from metadata

### CODE REVIEW

**Comment by skavanagh** [comment]
Should be able to use an IN statement like so with H2

```
PreparedStatement prep = conn.prepareStatement(
    "SELECT * FROM TABLE(X INT=?) T INNER JOIN TEST ON T.X=TEST.ID");
prep.setObject(1, new Object[] { "1", "2" });
ResultSet rs = prep.executeQuery();
```

as per http://www.h2database.com/html/performance.html#database_performance_tuning

**Comment by abn** [comment]
@skavanagh thank you for the fix, it is a welcome improvement. The changes look good to me, however a few minor non-functional changes will be appreciated.
- split out the _.gitignore_ commit
- White space usage consistency; the code changes use a mixture of spaces and tabs, use tabs (4 space).
- Query string formatting;  just for consistency, split the _PROPERTY_MATCH_ initialization and capitalize where required. Maybe something like:

``` java
        protected final static String PROPERTY_MATCH = "SELECT record, COUNT(record) as count "
                + "FROM TABLE(p varchar =  ?, v varchar = ? ) t INNER JOIN meta ON t.p = meta.prop AND t.v = meta.value "
                + "GROUP BY record";
```

**Comment by skavanagh** [comment]
Uhhh!! I think that made it worse.  I'll try again tonight, may have to give up and resort to using eclipse :smile:

**Comment by skavanagh** [comment]
Should be better now!  Thanks @abn!!

**Comment by abn** [comment]
@skavanagh thanks, i have merged the changes. Note I had fix up a few things.

**Comment by skavanagh** [comment]
Great! Thanks @abn!! Sorry about the whitespace issues.

**Pull request merged**
